#!/usr/bin/env node
// One-off: write character.json bios for the canonical P&P cast, the 8 suitors, and the Frost family.
// Bios distilled from characters/*.md and NEW_SUITORS_PROMPTS.md. Does NOT overwrite existing character.json.
const fs = require('fs');
const path = require('path');
const BASE = path.join(__dirname, 'worlds', 'pride-and-prejudice', 'characters');

const C = {
  // ---------- Canonical Pride & Prejudice cast ----------
  mr_darcy: { name: 'Mr. Darcy', archetype: 'The Proud Suitor',
    appearance: 'Tall and fastidious, gravely handsome in impeccable dark tailoring; a reserved, unsmiling bearing that does not invite approach.',
    definition: 'The proudest, most disagreeable man in the room — clever, reserved, and quick to judge, yet capable of deep self-examination beneath the defensive shell that a lifetime of deference has built. Ten thousand a year and a name to match, he is already half-caught by a wit sharper than his own. His story is pride slowly learning humility, drawn out of him by love.',
    voice: 'Formal, measured, and complete in syntax; he speaks less and weightily, distant and cutting at first, warmth surfacing only as feeling cracks the structure.',
    traits: ['Pride', 'Reserve', 'Integrity'] },
  miss_bingley: { name: 'Miss Bingley', archetype: 'The Rival',
    appearance: 'Fashionable and studiedly elegant, a beauty of £20,000 dressed at the height of town taste, her poise polished to a cold gleam.',
    definition: 'Caroline Bingley — calculating and status-obsessed, a refined veneer laid over envy and malice. Her ambition is social, her designs fixed on Darcy, and when thwarted her sweetness curdles into spite. Beneath her contempt for inferiors lies the terror that she herself is contemptible.',
    voice: 'Polished and controlled, compliments used as weapons; her cruelty arrives wrapped in the grammar of propriety — concern, observation, aesthetic judgment.',
    traits: ['Ambition', 'Vanity', 'Insincerity'] },
  mr_wickham: { name: 'Mr. Wickham', archetype: 'The Charming Officer',
    appearance: 'Strikingly handsome in a militia officer\'s scarlet regimentals, an easy open smile and a manner that invites instant trust.',
    definition: 'Charm as a full-body performance: everything on the surface is warm and confiding, underneath is mercenary calculation and no loyalty. Son of Darcy\'s late steward, he carries a grievance he wields like a blade — the story that Darcy cheated him of his inheritance. His amiability lasts exactly as long as it serves him.',
    voice: 'Smooth and confiding, a practiced ease that never stumbles; he keeps grievances light and agreeable, framing every choice as impulse or others\' fault, never calculation.',
    traits: ['Charm', 'Opportunism', 'Duplicity'] },
  mr_bingley: { name: 'Mr. Bingley', archetype: 'The Warm Host',
    appearance: 'Youthful, bright-faced and easy, dressed with cheerful good taste; a man who dances every dance and means every smile.',
    definition: 'Sunny, impulsive, and governed by the warmth of the present moment. A young man of large fortune newly settled at Netherfield, devoted to Jane and delighted by everyone. His amiability is his charm and his flaw both — safe with all, and therefore easily led by the friends he trusts.',
    voice: 'Unguarded and immediate — cheerful bursts in buoyant sentences, free of irony, every thought safe to share and every listener a friend.',
    traits: ['Amiability', 'Pliability', 'Sincerity'] },
  jane_bennet: { name: 'Jane Bennet', archetype: 'The Gentle Beauty',
    appearance: 'The acknowledged beauty of the county — serene, fair, and softly radiant, her composure concealing a depth of feeling.',
    definition: 'Gentle, trusting, and always inclined to the charitable reading, she is slow to suspect ill will and slower to voice displeasure. The eldest Bennet daughter, quietly in love with Bingley, she softens rooms rather than commands them. Her goodness is a kind of blindness — she cannot reconcile her faith in others with the evidence of their failings.',
    voice: 'Measured and mild, reluctant to assert or contradict; her sentences trail toward hopefulness or gentle demurral, understatement where others flare.',
    traits: ['Gentleness', 'Forbearance', 'Loyalty'] },
  mrs_bennet: { name: 'Mrs. Bennet', archetype: 'The Anxious Matchmaker',
    appearance: 'A handsome, fretful matron dressed a shade too eagerly for the occasion, forever scanning the room for her daughters\' prospects.',
    definition: 'Volatile, anxious, and single-minded, her whole existence has narrowed to the panic of marrying off her daughters before time runs out. She swings between giddy hope and bitter complaint at the mercy of matrimonial prospects. Beneath the foolishness is a genuine terror — she grasps the family\'s precarity more clearly than she admits.',
    voice: 'Breathless and insistent, lurching from grievance to excitement without pause; she repeats, interrupts, and escalates trivia into catastrophe.',
    traits: ['Anxiety', 'Vulgarity', 'Maternal Zeal'] },
  charlotte_lucas: { name: 'Charlotte Lucas', archetype: 'The Clear-Eyed Realist',
    appearance: 'Sensible and plainly elegant, about seven-and-twenty, with a calm, observant face that misses nothing at the edge of the room.',
    definition: 'Unsentimental, intelligent, resigned but not bitter — Sir William\'s eldest daughter and a shrewd observer of the marriage market she views as economics, not romance. To Arabella she reads as a canny almost-ally who will tell the unromantic truth about Darcy\'s consequence and the cost of crossing him. She knows exactly what she is doing and will not apologise.',
    voice: 'Measured and direct, plain matter-of-fact cadences that name uncomfortable truths without apology or self-pity — dry, even, unhurried.',
    traits: ['Pragmatism', 'Discernment', 'Loyalty'] },
  mr_collins: { name: 'Mr. Collins', archetype: 'The Pompous Clergyman',
    appearance: 'A heavy, solemn young clergyman in careful black, his air a strange blend of grovelling deference and self-important gravity.',
    definition: 'Pompous yet grovelling, utterly without self-awareness and earnest in his absurdities. Heir by entail to Longbourn and clergyman to Lady Catherine de Bourgh, he mistakes tolerance for approval and silence for admiration. He genuinely believes his obsequious attentions are a gift.',
    voice: 'Verbose and ceremonious — flattery layered onto formality in elaborate constructions that always circle back to his patroness, his position, or his own importance.',
    traits: ['Pomposity', 'Servility', 'Obliviousness'] },
  lydia_bennet: { name: 'Lydia Bennet', archetype: 'The Reckless Flirt',
    appearance: 'Fifteen, stout and well-grown with a fine complexion, brought out too early and forever laughing toward the officers.',
    definition: 'Impulsive, vain, and thoughtless, the youngest Bennet is ruled entirely by immediate gratification and an appetite for pleasure and officers that eclipses all prudence. She bursts into rooms with loud laughter and gossip. She mistakes attention for love and has no conception that her actions carry weight beyond the moment.',
    voice: 'Breathless and exclamatory, tumbling from thought to thought in run-on bursts of girlish enthusiasm, heedless of propriety or consequence.',
    traits: ['Impulsiveness', 'Vanity', 'Recklessness'] },
  elizabeth_bennet: { name: 'Elizabeth Bennet', archetype: 'The Witty Sister',
    appearance: 'Bright-eyed and quick, handsome rather than beautiful, with a lively, intelligent expression and an easy, unaffected grace.',
    definition: 'The second Bennet daughter — clever, playful, and sharp of judgment, Jane\'s closest confidante and Charlotte\'s old friend. In this telling she stands as recognisable atmosphere rather than the centre: the Darcy duel belongs to Arabella, so Elizabeth moves through the room as warmth and wit at the margin.',
    voice: 'Lively and archly playful, teasing where others flatter; a ready, ironic intelligence that enjoys the absurd and rarely misses a mark.',
    traits: ['Wit', 'Independence', 'Discernment'] },
  sir_william: { name: 'Sir William Lucas', archetype: 'The Genial Connector',
    appearance: 'A good-natured, ceremonious gentleman made harmlessly grand by a former presentation at court, beaming over the company.',
    definition: 'Charlotte\'s father and the neighbourhood\'s genial master of introductions — fond of rank and formal civility, well-meaning and easy to steer. He is the socially safe figure who can bring a newcomer into the room, and his allusion to a likely Bingley–Jane match is the remark that turns Darcy\'s eyes grave toward the dancing pair.',
    voice: 'Warm, formal, and a little grandiose; he delights in the ceremony of introductions and the elegance of the company.',
    traits: ['Geniality', 'Formality', 'Vanity of Rank'] },

  // ---------- The eight new suitors ----------
  lord_ravenscar: { name: 'Lord Sebastian Ravenscar', archetype: 'The Dark Viscount',
    appearance: 'Strikingly handsome and dark-haired with a sharp jaw, brooding grey eyes and a faint scar; black tailcoat, deep-wine waistcoat, a cravat loosened just enough to read as dangerous.',
    definition: 'A viscount of a vast northern estate — old title, darker fortune, wealth that whispers of gambling tables and duels. All danger and beautiful manners: to be seen on his arm is a triumph and a scandal waiting to happen. His immense fortune is rumoured half-mortgaged to his vices.',
    voice: 'Low, magnetic and unhurried, every courtesy edged with provocation — charm that dares you to disapprove.',
    traits: ['Magnetic', 'Reckless', 'Dangerous'] },
  sir_ashbourne: { name: 'Sir Henry Ashbourne', archetype: 'The Safe Harbour',
    appearance: 'A warm, distinguished gentleman of about forty, chestnut hair greying at the temples, gentle intelligent eyes, a well-cut bottle-green coat and a calm, assured posture.',
    definition: 'A baronet of a well-kept country seat — comfortable, unencumbered, respectable to the bone. A widower in his prime: sensible, generous, a little grave, and solidly wealthy with land that pays. The match every sensible mother prays for.',
    voice: 'Calm, kind and considered, plain-spoken without flourish — the steady reassurance of a man with nothing to prove.',
    traits: ['Steady', 'Kind', 'Dependable'] },
  capt_vane: { name: 'Captain Frederick Vane', archetype: 'The Self-Made Sailor',
    appearance: 'A rugged, confident naval captain in his early thirties, sun-bronzed with tousled dark-blond hair and keen blue eyes, in a gold-epauletted Royal Navy uniform and an easy weathered grin.',
    definition: 'A naval captain returned from the wars rich on prize-money — no old name, but a fortune won by his own hand. Sun-weathered, quick to laugh and quicker to act, with new money and no shame in it, which the drawing rooms have not forgiven.',
    voice: 'Bold, frank and good-humoured, salted with the directness of the quarterdeck; he says what he means and laughs easily.',
    traits: ['Bold', 'Proud', 'Frank'] },
  mr_devereux: { name: 'Monsieur Rafael Devereux', archetype: 'The Émigré',
    appearance: 'An elegant continental gentleman, olive-skinned with dark wavy hair and expressive eyes, in a beautifully tailored plum-and-silver French-cut coat with lace at the cuffs and a knowing half-smile.',
    definition: 'A French aristocrat in exile — a comte without his lands, living on a rescued fortune and impeccable charm. Cosmopolitan, cultured and dangerously fluent in flattery; no one is quite sure how much of him is true, nor whether his wealth is as large as it dazzles.',
    voice: 'Silken, cultivated and theatrical, flattery delivered like poetry; charming, unreadable, always a step ahead of the conversation.',
    traits: ['Charming', 'Enigmatic', 'Cultured'] },
  mr_hale: { name: 'Mr. Augustus Hale', archetype: 'The New Money',
    appearance: 'A robust, sharp-eyed young man of new wealth, close-cropped auburn hair and strong features, in a slightly-too-fine plum coat and a heavy gold watch-chain, standing with defiant assurance.',
    definition: 'Heir to a great manufacturing fortune from the north — no coat of arms, but more ready money than half the peerage. Modern, restless and unimpressed by titles, he buys what old families merely inherit and knows exactly how it grates on them.',
    voice: 'Blunt, quick and unsentimental, impatient with ceremony; he talks money and results where others talk pedigree.',
    traits: ['Ambitious', 'Blunt', 'Modern'] },
  mr_fenwick: { name: 'Mr. Thomas Fenwick', archetype: 'The Childhood Love',
    appearance: 'A gentle, handsome young man of modest means, soft brown hair and warm hazel eyes, an open honest face and a plain dark coat slightly worn at the cuffs — no jewels, a shy tender smile.',
    definition: 'A country curate\'s son with no land and no fortune — only a modest living and an old, old promise. The boy from next door, grown gentle and true, he has nothing to offer but a whole heart and the memory of who you were before the world got complicated.',
    voice: 'Warm, earnest and unpolished, sincerity without strategy; he speaks plainly of feeling and cannot dissemble.',
    traits: ['Devoted', 'Earnest', 'Sincere'] },
  ens_pryce: { name: 'Ensign Edward Pryce', archetype: 'The Idealist Officer',
    appearance: 'A fresh-faced young militia officer in his early twenties, neat sandy hair and bright earnest eyes, a scarlet regimental coat that is clearly his best and only fine thing, standing straight and eager.',
    definition: 'A junior militia ensign of good manners but no money, his commission bought on hope and a widowed mother\'s savings. Young, ardent, full of honour and empty of pounds — he would fight a duel for your glove and starve for your smile.',
    voice: 'Ardent and gallant, a little formal in his eagerness to do right; honest to a fault and easily moved to noble declarations.',
    traits: ['Brave', 'Naïve', 'Honourable'] },
  mr_quill: { name: 'Mr. Jasper Quill', archetype: 'The Penniless Poet',
    appearance: 'A lean romantic young poet with tousled dark curls and pale intense features, ink-stained fingers, a rumpled loosely-tied cravat and a threadbare but artful coat, a small book in hand.',
    definition: 'A gentleman by birth and a pauper by choice, he traded an inheritance for ink, verse and a garret. Beautiful, brilliant and utterly broke, he will write you into immortality and forget to pay the rent — living on unsold verses and the kindness of friends.',
    voice: 'Passionate and extravagant, speech tumbling into imagery and quotation; he feels everything at full pitch and budgets nothing.',
    traits: ['Passionate', 'Impractical', 'Romantic'] },

  // ---------- The Frost family ----------
  arabella_frost: { name: 'Arabella Frost', archetype: 'The Wit (Player)',
    appearance: 'A gentleman\'s daughter of modest fortune, keen-eyed and composed, dressed with quiet good taste; she meets a room with a raised eyebrow rather than a lowered gaze.',
    definition: 'The player character — a gentleman\'s daughter of modest fortune and immodest cleverness who arrives with sharper eyes than the room expects. She inherits Elizabeth\'s role in the Darcy duel: the outsider who refuses to be quietly measured and priced, and answers condescension with something colder still. Her weakness is a pride as quick as her tongue — she would rather wound than appear to care.',
    voice: 'Quick, dry and unafraid; she never leaves a clever cruelty unanswered and turns an intended slight into the laughter of the room.',
    traits: ['Sharp Wit', 'Large Spirit', 'Pride'] },
  mr_frost: { name: 'Mr. Frost', archetype: 'The Bookish Father',
    appearance: 'A quiet, dry-humoured gentleman of minor estate, more at ease among his books than in company, with an ironic light in his eye.',
    definition: 'Arabella\'s father — minor gentry of small fortune, a sharp mind who honed his daughter\'s wit in his own library. Detached and amused by the follies of the marriage market, he indulges Arabella\'s cleverness where his wife despairs of it.',
    voice: 'Dry, ironic and economical, fond of the sly aside; he says little but rarely wastes a word.',
    traits: ['Wry', 'Bookish', 'Detached'] },
  mrs_frost: { name: 'Mrs. Frost', archetype: 'The Worried Mother',
    appearance: 'A well-meaning, anxious matron whose smiles never quite settle, forever calculating her daughter\'s prospects at the marriage table.',
    definition: 'Arabella\'s mother — her anxieties live at the marriage table, and a small dowry and a clever, uncompromising daughter give her endless cause for worry. She loves Arabella and fears for her in equal, exhausting measure.',
    voice: 'Fretful and coaxing, quick to hope and quicker to despair; she urges prudence in a daughter constitutionally unable to supply it.',
    traits: ['Anxious', 'Well-Meaning', 'Prudent'] },

  // ---------- Minor / experimental folders (light world-fitting stubs) ----------
  julian_vane: { name: 'Julian Vane', archetype: 'The Idle Younger Brother',
    appearance: 'A polished, indolent young gentleman with the Vane good looks worn more carelessly — fashionable dress, a languid, amused air.',
    definition: 'A younger relation of Captain Vane\'s line who never went to sea — charming, idle, and content to spend a fortune he did not earn. He drifts through drawing rooms trading on the family name and his own easy looks.',
    voice: 'Languid and teasing, all surface charm and lazy irony; he flirts as reflex and commits to nothing.',
    traits: ['Idle', 'Charming', 'Feckless'] },
  miss_vere: { name: 'Miss Vere', archetype: 'The Proud Beauty',
    appearance: 'An elegant, cool-mannered young lady of fashion, beautiful and aware of it, dressed at the height of taste.',
    definition: 'A well-connected young lady of good family and better opinion of herself, accustomed to being the finest thing in any room. Proud, decorative and quick to condescend, she measures newcomers by their settlements.',
    voice: 'Cool and gracious on the surface, faintly condescending beneath; her civility is a way of keeping others at their proper distance.',
    traits: ['Proud', 'Fashionable', 'Aloof'] },
  miss_vere_ruined: { name: 'Miss Vere (Disgraced)', archetype: 'The Fallen Beauty',
    appearance: 'The same fashionable beauty undone — pale and hollow-eyed, her fine dress now a reproach, the room\'s regard turned to whispers.',
    definition: 'Miss Vere after scandal has done its work: the proud beauty cast out of the society she once ruled. Stripped of her standing, she is by turns brittle, defiant, and desperate — a cautionary shadow of who she was.',
    voice: 'Brittle and defensive, old hauteur cracking into bitterness or pleading; pride and shame at war in every line.',
    traits: ['Disgraced', 'Defiant', 'Desperate'] },
  mr_ashford: { name: 'Mr. Ashford', archetype: 'The Respectable Gentleman',
    appearance: 'A composed, well-dressed gentleman of settled means, agreeable features and correct, unremarkable manners.',
    definition: 'A gentleman of comfortable property and unimpeachable respectability — sensible, courteous, and just a little dull. The sort the neighbourhood approves of without quite remembering afterward.',
    voice: 'Correct and even-tempered, courteous without warmth; he speaks in the safe, agreeable phrases of good society.',
    traits: ['Respectable', 'Reserved', 'Conventional'] },
  mr_ashford_worn: { name: 'Mr. Ashford (Careworn)', archetype: 'The Fallen-on-Hard-Times Gentleman',
    appearance: 'The same gentleman diminished — a coat gone shabby at the seams, a tired, anxious face, the polish of prosperity rubbed away.',
    definition: 'Mr. Ashford after misfortune: property lost or dwindled, the easy respectability now a struggle to keep up appearances. Careworn and proud, he clings to the manners of a station he can no longer afford.',
    voice: 'Guarded and strained, courtesy worn thin over worry; he deflects questions of circumstance with weary dignity.',
    traits: ['Careworn', 'Proud', 'Diminished'] },
  mr_coyle: { name: 'Mr. Coyle', archetype: 'The Grasping Man of Business',
    appearance: 'A sharp, watchful man in sober but expensive dress, quick eyes forever pricing the room and its occupants.',
    definition: 'A man of business and few scruples who has made money enough to buy his way toward gentility. Shrewd, acquisitive, and coldly polite, he treats acquaintance as investment and sentiment as weakness.',
    voice: 'Clipped and transactional, courteous only where it profits him; he turns every exchange toward advantage.',
    traits: ['Grasping', 'Shrewd', 'Cold'] },
  the_father: { name: 'The Father', archetype: 'The Stern Patriarch',
    appearance: 'An older gentleman of grave authority, plainly and correctly dressed, with the immovable bearing of a man used to being obeyed.',
    definition: 'A father who rules his household by expectation and duty, weighing prospects and propriety above his children\'s wishes. His approval is hard-won and his disappointment quietly devastating.',
    voice: 'Grave and authoritative, sparing of praise; he speaks in judgments and expects them to settle the matter.',
    traits: ['Authoritative', 'Dutiful', 'Exacting'] },
  the_maid: { name: 'The Maid', archetype: 'The Confidante Below Stairs',
    appearance: 'A neat young servant in a plain cap and apron, quick-handed and quiet-footed, eyes lowered but missing nothing.',
    definition: 'A lady\'s maid who sees the household from below stairs — discreet, observant, and privy to secrets her mistress would not speak aloud. Loyal but not blind, she is the small, steady presence at the edge of every private scene.',
    voice: 'Soft and deferential, plain-spoken in private; she offers homely truth when the drawing-room manner is dropped.',
    traits: ['Discreet', 'Observant', 'Loyal'] },
};

let wrote = 0, skipped = 0, missing = 0;
for (const folder of Object.keys(C)) {
  const dir = path.join(BASE, folder);
  if (!fs.existsSync(dir)) { console.log('  (no folder) ' + folder); missing++; continue; }
  const file = path.join(dir, 'character.json');
  if (fs.existsSync(file)) { console.log('  skip (exists) ' + folder); skipped++; continue; }
  const rec = Object.assign({ folder }, C[folder], { brief: '', created: new Date().toISOString() });
  // put name/folder first for readability
  const ordered = { name: rec.name, folder: rec.folder, archetype: rec.archetype, appearance: rec.appearance, definition: rec.definition, voice: rec.voice, traits: rec.traits, brief: rec.brief, created: rec.created };
  fs.writeFileSync(file, JSON.stringify(ordered, null, 2));
  console.log('  wrote ' + folder);
  wrote++;
}
console.log(`\nDone. wrote=${wrote} skipped=${skipped} missing=${missing}`);
